# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
    docker:
      - image: circleci/node:11.10
    working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: 
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: 
          name: Run tests
          command: npm run test 
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  now --token $ZEIT_TOKEN --team $ZEIT_TEAM --local-config .now/now.prod.json
              fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master